# Generated by Django 4.2.7 on 2024-02-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeninsightt', '0002_comment_movie_watchlist_reply_likedmovies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedmovies',
            old_name='LikedMovies',
            new_name='LikedMovie',
        ),
    ]
