# Generated by Django 4.2.7 on 2024-02-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screeninsightt', '0004_movie_movieid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
