# Generated by Django 4.2.7 on 2024-02-13 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('screeninsightt', '0005_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='headline',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
