# Generated by Django 4.2.7 on 2024-02-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screeninsightt', '0006_comment_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='poster_path',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
