# Generated by Django 4.2.7 on 2024-02-19 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screeninsightt', '0007_comment_poster_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenttv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=5000)),
                ('rating', models.IntegerField(null=True)),
                ('poster_path', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=5000)),
                ('movieid', models.CharField(max_length=10, null=True)),
                ('comments', models.ManyToManyField(to='screeninsightt.comment')),
            ],
        ),
        migrations.CreateModel(
            name='WatchListtv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WatcheListMovies', models.ManyToManyField(to='screeninsightt.tv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Replytv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('RepliedToComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screeninsightt.commenttv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likedtv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikedMovie', models.ManyToManyField(to='screeninsightt.tv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commenttv',
            name='CommentedOnMovie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screeninsightt.tv'),
        ),
        migrations.AddField(
            model_name='commenttv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
